Electif/Frontend/Controllers/ElectiveController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Frontend.Helpers;
using System.Linq;
using Frontend.OpenXml;
using Microsoft.AspNetCore.Authorization;
using Service.Models;
using Frontend.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Frontend.Controllers
{
    public class ElectiveController : BaseController
    {

        public ElectiveController(IClientBuilder clientBuilder) : base(clientBuilder)
        { }

        public async Task<IActionResult> Index()
        {
            using (var client = ElectiveClient())
            {
                bool parsed = int.TryParse(User.Claims.FirstOrDefault(c => c.Type.Equals("Id"))?.Value, out int id);
                if (!parsed || User.IsInRole("Admin") || User.IsInRole("Teacher"))
                {
                    var electives = await client.Get();
                    return View(electives);
                }

                using (var studentClient = StudentClient())
                {
                    var user = await studentClient.GetById(id);
                    var electives = await client.GetByGroup(user.Group.Id);
                    return View("AvailableElectives", electives);
                }
            }
        }

        [Authorize(Roles = "Admin,Teacher")]
        public async Task<IActionResult> Create()
        {
            using (var teacherClient = TeacherClient())
            using (var groupClient = GroupClient())
            {
                var teachers = await teacherClient.Get();
                var groups = await groupClient.Get();
                var teachersList = new SelectList(teachers.Select(t => new { t.Id, Name = t.ToString() }), "Id", "Name");
                var groupsList = new SelectList(groups, "Id", "Name");
                return View(new CreateElectiveModel { Teachers = teachersList, Groups = groupsList });
            }
        }

        public async Task<IActionResult> AvailableElectives()
        {
            using (var client = ElectiveClient())
            {
                bool parsed = int.TryParse(User.Claims.FirstOrDefault(c => c.Type.Equals("Id"))?.Value, out int id);
                if (!parsed || User.IsInRole("Admin") || User.IsInRole("Teacher"))
                {
                    var electives = await client.Get();
                    return View("Index", electives);
                }

                using (var studentClient = StudentClient())
                {
                    var user = await studentClient.GetById(id);
                    var electives = await client.GetByGroup(user.Group.Id);
                    return View(electives);
                }
            }
        }

        public async Task<IActionResult> Subscribe(int? id)
        {
            bool parsed = int.TryParse(User.Claims.FirstOrDefault(c => c.Type.Equals("Id"))?.Value, out int i);
            if (!id.HasValue || !parsed)
                return RedirectToAction("AvailableElectives");

            using (var studentClient = StudentClient())
            {
                var user = await studentClient.GetById(i);
                var electives = await studentClient.Subscribe(i, id.Value);
            }
            return RedirectToAction("AvailableElectives");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            using (var client = ElectiveClient())
            {
                ElectiveDto elective = await client.GetById(id.Value);
                if (elective == null)
                {
                    var electives = await client.Get();
                    return View("Index", electives);
                }
                return View(elective);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Teacher")]
        public async Task<ActionResult> Create(CreateElectiveModel model)
        {
            if (ModelState.IsValid)
            {
                model.Elective.Teacher = new TeacherDto {Id = model.SelectedTeacherId};
                model.Elective.Groups = new List<GroupDto> { new GroupDto {Id = model.SelectedGroupId}};
                using (var client = ElectiveClient())
                {
                    await client.Add(model.Elective);
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        [Authorize(Roles = "Admin,Teacher")]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Download(int electiveId)
        {
            using (var electiveClient = ElectiveClient())
            {
                ElectiveDto elective = await electiveClient.GetById(electiveId);
                string path = GenerateExcelClient.GenerateDocument(elective);
                var memory = new MemoryStream();
                await using (var stream = new FileStream(path, FileMode.Open))
                {
                    await stream.CopyToAsync(memory);
                }
                memory.Position = 0;
                return File(memory, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Path.GetFileName(path));
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                RedirectToAction("Index");
            }

            using (var electiveClient = ElectiveClient())
            {
                ElectiveDto electiveDto = await electiveClient.Delete(id.Value); // Http request
                if (electiveDto == null)
                {
                    RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddGroup(int electiveId)
        {
            using (var groupClient = GroupClient())
            using (var electiveClient = ElectiveClient())
            {
                var groups = await groupClient.Get();
                var elective = await electiveClient.GetById(electiveId);
                var filtered = new List<GroupDto>();

                foreach (var group in groups)
                {
                    if (elective.Groups.FirstOrDefault(g => g.Id == group.Id) == null)
                        filtered.Add(group);
                }

                var groupList = new SelectList(filtered, "Id", "Name");

                var model = new AddGroupElectiveViewModel { Elective = elective, Groups = groupList };
                return View(model);
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddGroup(AddGroupElectiveViewModel model)
        {
            using (var electiveClient = ElectiveClient())
            {
                await electiveClient.AddGroup(model.ElectiveId, model.SelectedGroupId);
                return RedirectToAction("AddGroup", new { electiveId = model.ElectiveId });
            }
        }
    }
}

Electif/Frontend/Controllers/GroupController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Frontend.Helpers;
using Frontend.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Models;

namespace Frontend.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GroupController : BaseController
    {
        public GroupController(IClientBuilder clientBuilder) : base(clientBuilder)
        { }

        public async Task<IActionResult> Index()
        {
            using (var groupClient = GroupClient())
            {
                List<GroupDto> groups = await groupClient.Get();
                return View(groups);
            }
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return View("Index");

            using (var groupClient = GroupClient())
            {
                GroupDto group = await groupClient.GetById(id.Value);
                if (group == null)
                    return View("Index");

                return View(group);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GroupDto group)
        {
            if (ModelState.IsValid)
            {
                using (var groupClient = GroupClient())
                {
                    await groupClient.Update(group);
                    return RedirectToAction("Index");
                }
            }
            return View(group);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return View("Index");
            }

            using (var groupClient = GroupClient())
            {
                GroupDto group = await groupClient.GetById(id.Value);
                if (group == null)
                {
                    return View("Index"); // Handle this    
                }
                return View(group);
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return View("Index");
            }

            using (var groupClient = GroupClient())
            {
                GroupDto group = await groupClient.Delete(id.Value); // Http request
                if (group == null)
                {
                    return View("Index"); // Handle this    
                }

                return RedirectToAction("Index");
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Service.Models.GroupDto group)
        {
            if (ModelState.IsValid)
            {
                using (var groupClient = GroupClient())
                {
                    await groupClient.Add(group);
                    return RedirectToAction("Index");
                }
            }
            return View(group);
        }
    }
}

Electif/Frontend/Controllers/UserController.cs
using System.Linq;
using System.Threading.Tasks;
using Frontend.Helpers;
using Frontend.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Service.Models;

namespace Frontend.Controllers
{
    public class UserController : BaseController
    {
        public UserController(IClientBuilder clientBuilder) : base(clientBuilder)
        { }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            using (var adminClient = AdminClient())
            using (var studentClient = StudentClient())
            using (var teacherClient = TeacherClient())
            {
                var admins = await adminClient.Get();
                var students = await studentClient.Get();
                var teachers = await teacherClient.Get();

                var model = new UserModels
                {
                    Admins = admins,
                    Teachers = teachers,
                    Students = students,
                };

                return View(model);
            }
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            using (var userClient = UserClient())
            {
                var response = await userClient.Login(model, Response.Cookies);

                if (response != null)
                {
                    await HttpContext.SignInAsync(response);
                    return Redirect("/");
                }
                else
                {
                    ModelState.AddModelError("Password", "Invalid email or password");
                    model.Password = "";
                    return View(model);
                }
            }
        }

        public async Task<IActionResult> Profile(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            string role = null;
            using (var userClient = UserClient())
            {
                role = await userClient.GetRole(id.Value);
            }
            if (role == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if (role.Equals("Student"))
            {
                using (var studentClient = StudentClient())
                {
                    StudentDto student = await studentClient.GetById(id.Value);
                    if (student == null)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    return View(new UserProfileModel() { User = student, Electives = student.Electives, PendingElectives = student.PendingElectives, Group = student.Group, Role = role});
                }
            }
            else if (role.Equals("Admin"))
            {
                using (var adminClient = AdminClient())
                {
                    AdminDto admin = await adminClient.GetById(id.Value);
                    if (admin == null)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    return View(new UserProfileModel() { User = admin, Role = role });
                }
            }
            if (role.Equals("Teacher"))
            {
                using (var teacherClient = TeacherClient())
                {
                    TeacherDto teacher = await teacherClient.GetById(id.Value);
                    if (teacher == null)
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    return View(new UserProfileModel() { User = teacher, Electives = teacher.Electives, Role = role });
                }
            }
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            Response.Cookies.Delete("jwt");
            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            using (var groupClient = GroupClient())
            {
                var groups = await groupClient.Get();
                var groupsList = new SelectList(groups, "Id", "Name");

                return View(new CreateUserModel() { Groups = groupsList });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create(CreateUserModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.RegisterModel.Type == "Admin")
                {
                    RegisterModel rm = model.RegisterModel;
                    using (var client = AdminClient())
                    {
                        await client.Add(new AdminDto()
                        {
                            Firstname = rm.Firstname,
                            Lastname = rm.Lastname,
                            Email = rm.Email,
                            Password = rm.Password
                        });
                        return RedirectToAction("Index");
                    }
                } else if (model.RegisterModel.Type == "Teacher")
                {
                    RegisterModel rm = model.RegisterModel;
                    using (var client = TeacherClient())
                    {
                        await client.Add(new TeacherDto()
                        {
                            Firstname = rm.Firstname,
                            Lastname = rm.Lastname,
                            Email = rm.Email,
                            Password = rm.Password
                        });
                        return RedirectToAction("Index");
                    }
                } else if (model.RegisterModel.Type == "Student")
                {
                    RegisterModel rm = model.RegisterModel;
                    using (var client = StudentClient())
                    {
                        await client.Add(new StudentDto()
                        {
                            Firstname = rm.Firstname,
                            Lastname = rm.Lastname,
                            Email = rm.Email,
                            Password = rm.Password,
                            UserId = rm.UserId,
                            Group = new GroupDto() { Id = rm.GroupId }
                        });
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(model);
        }
    }
}

Electif/Frontend/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Electif EPITA</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Electif EPITA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        @if (User?.Identity?.IsAuthenticated == true)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Group" asp-action="Index">Groupes</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Utilisateurs</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Elective" asp-action="Index">Electifs</a>
                            </li>
                            var name = User.Claims.FirstOrDefault(c => c.Type.Equals(ClaimTypes.GivenName))?.Value + " " + User.Claims.FirstOrDefault(c => c.Type.Equals(ClaimTypes.Name))?.Value;
                            <li class="nav-item">
                              
                                    <a class="nav-link text-dark" asp-controller="User" asp-action="Profile" asp-route-id=@User.Claims.FirstOrDefault(c => c.Type.Equals("Id"))?.Value>Bienvenue @name</a>
                               
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Logout">Déconnexion</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Login">Connexion</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - EPITA
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>